- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      tsconfig.spec.json
      package-lock.json
      karma.conf.js
    TargetFolder: '$(Build.ArtifactStagingDirectory)'